APPIOS-2737: Clean up sdk
paysera/swift-lib-recurring-payments-sdk pull request #5
Opened 2021-03-03 15:31 UTC by Pattio

2021-03-04 03:07 UTC, softwaresaiyajin requested changes

2021-03-04 03:07 UTC, softwaresaiyajin commented on Sources/PayseraRecurringPaymentsSDK/Services/RecurringPaymentsApiRequestRouter.swift
> +        case _ where method == .post,
I've seen that you changed this to the code below in your previous PRs, let's apply it here as well.
```
switch method {
     case .post, 
              .put:
     ....
}
```

2021-03-08 11:32 UTC, Pattio commented on Sources/PayseraRecurringPaymentsSDK/Services/RecurringPaymentsApiRequestRouter.swift
> +        case _ where method == .post,
✅

2021-03-09 03:14 UTC, softwaresaiyajin approved these changes

2021-03-09 05:32 UTC, mildamauricaite approved these changes

2021-03-09 08:11 UTC, merged